// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "RS-AWS Product Shop API",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "Get all products",
        "description": "",
        "operationId": "getProducts.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "All products.",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "500": {
            "description": "Server error."
          }
        }
      },
      "post": {
        "summary": "Create a new product",
        "description": "",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateProductDTO"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "New product created.",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "400": {
            "description": "One or more inputs are invalid or missing."
          },
          "500": {
            "description": "Server error."
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "Get product by productId",
        "description": "",
        "operationId": "getProductById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Found product with given productId.",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "400": {
            "description": "Product id is invalid or missing in the paramater."
          },
          "404": {
            "description": "Product not found."
          },
          "500": {
            "description": "Server error."
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "count": {
          "title": "Product.count",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        }
      },
      "required": [
        "id",
        "count",
        "description",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "CreateProductDTO": {
      "properties": {
        "count": {
          "title": "CreateProductDTO.count",
          "type": "number"
        },
        "description": {
          "title": "CreateProductDTO.description",
          "type": "string"
        },
        "price": {
          "title": "CreateProductDTO.price",
          "type": "number"
        },
        "title": {
          "title": "CreateProductDTO.title",
          "type": "string"
        }
      },
      "required": [
        "count",
        "description",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "CreateProductDTO",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};