service: product-service
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs14.x
    stage: dev
    region: us-east-1

plugins:
    - serverless-webpack

functions:
    getProductsList:
        handler: src/handlers/getProductsList.handler
        events:
            - httpApi:
                  path: /products
                  method: get
    getProductsById:
        handler: src/handlers/getProductsById.handler
        events:
            - httpApi:
                  path: /products/{productId}
                  method: get

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true
